---

- name: Install cockpit-machines
  package:
    name: cockpit-machines
    state: present

- name: Install virt-viewer
  package:
    name: virt-viewer
    state: present

- name: Enable cockpit
  systemd:
    name: cockpit.socket
    enabled: true
    state: started

