---
## This playbook configures a host for provisioning openshift

# Configure 
- name: Provision KVM capability
  hosts: kvm-hosts
  remote_user: "{{ remote_user }}"
  become: yes

  roles:
  - subscription-manager
